name: learn-github-actions

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Message
        run: echo "Start Creating an image with Dockerfile"
      - name: Build the Docker image
        run: docker build . --file Dockerfile.dev --tag docker-react-app
      - name: Docker container run
        run: docker run -d docker-react-app yarn test
      # Node 16 버전을 사용합니다.
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      # yarn을 설치합니다.
      - name: Install Yarn
        run: npm install yarn
        
      - name: yarn berry
        run: yarn set version berry

      # 설치된 yarn을 통해 패키지를 설치합니다.
      - name: Install dependencies
        run: yarn

      # 테스트를 수행합니다.
      - name: Run tests
        run: yarn test

      # 앞의 작업이 실패/성공과 관계 없이 컨테이너들을 종료합니다.
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
      - name: Test Complete Message
        run: echo "Test Success"
