name: learn-github-actions

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Message
        run: echo "Start Creating an image with Dockerfile"
      - name: Build the Docker image
        run: docker build . --file Dockerfile.dev --tag docker-react-app
      - name: Test
        run: docker run -i docker-react-app yarn test && exit
      - name: Test Complete Message
        run: echo "Test Success"
