name: learn-github-actions

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: echo "Start Creating an image with Dockerfile" && \
          docker build . --file Dockerfile.dev --tag docker-react-app

  test:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: docker run docker-react-app yarn test -- --coverage

      - name: Test Complete
        run: echo "Test Success"
