name: learn-github-actions

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: yarn test
      - name: Test Complete Message
        run: echo "Test Success"

      # build:
      #   needs: tests
      #   runs-on: ubuntu-latest
      #   steps:
      #     - uses: actions/checkout@v2
      - name: Build Message
        run: echo "Start Creating an image with Dockerfile"
      - name: Build the Docker image
        run: docker build . --file Dockerfile.dev --tag docker-react-app
